name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2️⃣ Node.js no runner
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.15.0'

      # 3️⃣ Instala dependências (gera node_modules)
      - name: Install Dependencies (runner)
        run: yarn install --frozen-lockfile

      # 4️⃣ Gera Prisma Client
      - name: Generate Prisma client (runner)
        run: npx prisma generate

      # 5️⃣ Build definitivo
      - name: Build (runner)
        run: yarn build

      # 6️⃣ Copia TUDO para o servidor (incluindo node_modules)
      - name: Copy project to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules/.cache"
          target: "~/instrutorBackend"

      # 7️⃣ Apenas executar Prisma + restart (SEM yarn install)
      - name: Restart API on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/instrutorBackend
            npx prisma migrate deploy
            pm2 restart server
